server:
  port: 8089

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/admin/**, /auth/**, /api/users/**

        - id: doctorservice
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/doctor/**

        - id: appointmentservice
          uri: http://localhost:8012
          predicates:
            - Path=/api/v1/slots/**, /api/v1/appointments/**

        - id: categoryservice
          uri: http://localhost:8015
          predicates:
            - Path=/api/v1/category/**




jwt:
  secret: Z0ZqQm1nQ0tZQ1N2R3p3VjVnQ0hFZ3pMZ1R2aD...

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
