server:
  port: 8089

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: userservice
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/admin/**, /auth/**, /api/users/**

        - id: doctorservice
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/doctor/**

        - id: appointmentservice
          uri: http://localhost:8012
          predicates:
            - Path=/api/v1/slots/**, /api/v1/appointments/**

        - id: categoryservice
          uri: http://localhost:8015
          predicates:
            - Path=/api/v1/category/**

        - id: productservice
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/product/**
        - id: notificationservice
          uri: http://localhost:8017
          predicates:
            - Path=/api/v1/notifications/**
        - id: documentservice
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/documents/**






jwt:
  secret: Z0ZqQm1nQ0tZQ1N2R3p3VjVnQ0hFZ3pMZ1R2aD...

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
